// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx src/scripts/seed-patients.ts",
  },
  datasource: {
    // 빌드 시점에 DATABASE_URL이 없을 경우 더미 URL 사용 (prisma generate 통과용)
    url: process.env["DATABASE_URL"] ?? "postgresql://postgres:postgres@localhost:5432/postgres",
  },
});
